apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  labels:
    app: ingress-nginx

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
      - http:
          paths:
            - path: /test
              pathType: Prefix
              backend:
                service:
                  name: movie-service
                  port:
                    number: 80
