apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 1
  # 2. How do want to update the pods?
  #strategy: Recreate

  # 3. Which pods are managed by this deployment?
  selector:
    # This must match the labels we set on the pod!
    matchLabels:
      deploy: movie-pod
  # Everything under the template key is a regular pod specification.
  # nested inside the deployment spec
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        deploy: movie-pod
    spec:
      containers:
        - name: movie
          image: movie:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: movie-secret
                  key: spring.datasource.password
          ports:
            - containerPort: 8080
