apiVersion: v1
kind: Service
metadata:
  name: movie-service
spec:
  # Expose the service on a static port on each node
  # so that we can access the service from outside the cluster
  type: NodePort

  # When the node receives a request on the static port (30163)
  # selects pods with the label 'deploy:movie-pod'
  # and forwards the request to one of them
  selector:
    deploy: movie-pod

  # NodePort: direct connection from outside
  # Three types of ports for a service
  #  ports:
  #    # Static port assigned on each node
  #    - nodePort: 30163
  #    # Port exposed internally in the cluster
  #      port: 8080
  #    # The container port to send requests to
  #      targetPort: 8080

  # Called from ingress
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
